### ISSUE TITLE
Error: name 'FM_lr' is not defined

### ISSUE THREAD

**Issue by cbehren** [doogesh/super_resolution_emulator#1]
Hi, I was trying to execute the code on some simple test problem, and I find that FM_lr and FM_ic are not defined, but used in the notebook. In the current version, this is about cell [17], the last lines of the first "with" block. Is it possible that some necessary parts of the code were not pushed to the repo?
Best regards, Christoph.

**Comment by doogesh** [comment]
Thanks for pointing this out.
I have removed those lines. They are not required for this minimal working example.
